### ISSUE TITLE
old entities and new entities when updating the integration

### ISSUE THREAD

**Issue by rodrigonogueras** [radical-squared/aquatemp#65]
Hello,

I have th eintegration but sometimes, when you update the integration, all the old entities are deprecated and new ones are created and I have to modify all the automations. Is there a way to keep them from changing?

![image](https://github.com/radical-squared/aquatemp/assets/78388686/6ddb8921-bc16-482e-96d0-4df85b8a56ae)

![image](https://github.com/radical-squared/aquatemp/assets/78388686/f9789790-d570-47a0-9164-d4a8ddfedec2)

**Comment by elad-bar** [comment]
can you pls share diagnostic file?

thanks

**Comment by rodrigonogueras** [comment]
Sure @elad-bar 

HEre they are.
[home-assistant_aqua_temp_2023-07-17T11-46-24.396Z.log](https://github.com/radical-squared/aquatemp/files/12068813/home-assistant_aqua_temp_2023-07-17T11-46-24.396Z.log)

**Comment by elad-bar** [comment]
please check latest version [v3.0.23](https://github.com/radical-squared/aquatemp/releases/tag/v3.0.23), I think the issue is related to typo I had within the class that defines the key of the device name, it might require removing the integration and re-adding it after update to latest version and restart HA.

please let me know if it solved the issue,
thanks

**Comment by rodrigonogueras** [comment]
Hello @elad-bar.

I updated from 3.0.22 to 3.0.23. I remove the integration and add it again. I have to wait to future updates to check if the names are changed or not.

I also changed the password.

Thanks for your help. We can close the request.
